const channels = [
  '#matt22881',
  '#stryke66',
  '#outtapocketgamingg',
  // '#alun27gaming',
  '#bewareclips',
  // '#captaindabbeard',
  // '#c4vsavage',
  // '#dabsterreaper12',
  // '#detroit_ttv',
  // '#doeslayer',
  // '#featherylily275',
  // '#jilinxy',
  // '#kainecloud',
  // '#lordvalgaming',
  // '#lumberjerks',
  '#maverickaa2100',
  // '#mattbot22881',
  // '#notmatt22881',
  // '#optimusslimetv',
  '#optvail',
  '#pandapickle701',
  // '#patrickbeckman',
  // '#power9nov',
  // '#renegadesrage',
  // '#patrickbeckman',
  // '#serenityvargr',
  // '#shieldm8den',
  '#stabbytheclown',
  // '#surferttv',
  '#synasian1371',
  // '#ta3got3m',
  '#taintedtranquility',
  '#titan_gtv',
  // '#tlanaton',
  '#treylo20',
  // '#turnup_opg',
]
export default channels
