const channels = [
  '#matt22881',
  '#titan_gtv',
  // '#stryke66',
  // '#outtapocketgamingg',
  // // '#alun27gaming',
  // // '#bewareclips',
  // '#bigbeardh_',
  // // '#captaindabbeard',
  // // '#c4vsavage',
  // // '#dabsterreaper12',
  // // '#detroit_ttv',
  // // '#doeslayer',
  // // '#featherylily275',
  // // '#jilinxy',
  // // '#kainecloud',
  // // '#lordvalgaming',
  // // '#lumberjerks',
  // '#maverickaa2100',
  // // '#mattbot22881',
  // // '#notmatt22881',
  // // '#obongattv',
  // // '#optimusslimetv',
  // '#optvail',
  // '#pandapickle701',
  // // '#patrickbeckman',
  // // '#power9nov',
  // // '#renegadesrage',
  // // '#patrickbeckman',
  // // '#serenityvargr',
  // // '#shieldm8den',
  // // '#stabbytheclown',
  // // '#surferttv',
  // // '#synasian1371',
  // // '#ta3got3m',
  // '#taintedtranquility',
  // // '#tlanaton',
  // '#treylo20',
  // '#turnup_opg',
]
export default channels
