exports.run = (client, message, args, user, channel, self) => {

  client.say(channel,
    `
    titang5Gaim
    HSWP
    titang5Gaim
    HSWP
    titang5Gaim
    treyloOHYEAH
    beware14LG
    renega77Hype
    pandap43GG
    pandap43GG
    pandap43GG
    renega77Hype
    beware14LG
    treyloOHYEAH
    treyloOHYEAH
    beware14LG
    renega77Hype
    treyloTFAM
    treyloTFAM
    treyloTFAM
    renega77Hype
    beware14LG
    treyloOHYEAH
    pandap43GG
    titang5Gaim  
    pandap43GG
    titang5Gaim  
    pandap43GG  
    titang5Gaim  
    pandap43GG
   `
  )
}
