exports.run = (client, message, args, user, channel, self) => {

  client.say(channel,
  `
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLetem

  `
  )
}
