exports.run = (client, message, args, user, channel, self) => {

  client.say(channel,
  `
  obongaOtipa
  obongaLetem
  obongaLuv
  obongaOuttaHere
  obongaBeaker
  obongaOtipa
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLuv
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaBeaker
  obongaOtipa
  obongaLetem
  obongaLetem
  obongaLetem
  obongaLuv
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOtipa
  `
  )
}
