exports.run = (client, message, args, user, channel, self) => {

  client.say(channel,
  `
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere
  obongaOuttaHere 
  `
  )
}
