exports.run = (client, message, args, user, channel, self) => {

  client.say(channel,
    `
    treyloOHYEAH
    treyloOHYEAH
    treyloOHYEAH
    treyloOHYEAH
    treyloOHYEAH
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    beware14LG
    beware14LG
    beware14LG
    beware14LG
    beware14LG
    beware14LG
    beware14LG
    beware14LG
    beware14LG
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    `
  )

}
