exports.run = (client, message, args, user, channel, self) => {

  client.say(channel,
    `
    stryke32MillieLuv
    stryke32MillieLuv
    stryke32RIP
    stryke32RIP
    stryke32MillieLuv
    stryke32MillieLuv
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    stryke32Cheers
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    TombRaid
    `
  )

}
