exports.run = (client, message, args, user, channel, self) => {

    client.say(channel,
      `
      titang5Gaim
      titang5Gaim
      titang5Gaim
      titang5Gaim
      titang5Gaim
      TombRaid
      TombRaid
      TombRaid
      titang5Gaim
      titang5Gaim
      titang5Gaim
      TombRaid
      TombRaid
      TombRaid
      TombRaid
      TombRaid
      TombRaid
      titang5Gaim
      titang5Gaim
      titang5Gaim
      TombRaid
      TombRaid
      TombRaid
      TombRaid
      TombRaid
      TombRaid
      titang5Gaim
      titang5Gaim
      titang5Gaim
      TombRaid
      `
    )
  }
